# The main project repository https://github.com/sclorg/s2i-python-container.git
# uses CentOS-CI, Travis is not enabled at this moment.
# The purpose of this file is to add possibility of an alternative CI service
# in repository forks.

sudo: required

services: 
  - docker

language: go

go: latest

before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install -y go-md2man

install: 
  - go get github.com/openshift/source-to-image
  - pushd ${GOPATH}/src/github.com/openshift/source-to-image
  - export PATH=$PATH:${GOPATH}/src/github.com/openshift/source-to-image/_output/local/bin/linux/amd64/
  - hack/build-go.sh
  - popd
  - pip install --user distgen

script: DG=dg SKIP_SQUASH=1 make test TARGET=centos
