name: RHEL7-tests@TF

on:
  issue_comment:
    types:
      - created
jobs:
  build:
    # This job only runs for '[test]' pull request comments by owner, member
    name: Schedule test on Testing Farm service for RHEL7
    runs-on: ubuntu-20.04
    if: |
      github.event.issue.pull_request
      && contains(github.event.comment.body, '[test]')
      && contains(fromJson('["OWNER", "MEMBER"]'), github.event.comment.author_association)
    outputs:
      REQ_ID: ${{steps.sched_test.outputs.REQ_ID}}
      SHA: ${{steps.sha.outputs.SHA}}
    steps:
      - name: Get pull request number
        id: pr_nr
        run: |
          PR_URL="${{ github.event.comment.issue_url }}"
          echo "::set-output name=PR_NR::${PR_URL##*/}"

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ steps.pr_nr.outputs.PR_NR }}/head"

      - name: Get sha
        id: sha
        run: |
          # Store SHA into outputs
          echo "::set-output name=SHA::$(git rev-parse HEAD)"

      - name: Create status check to pending for RHEL7
        id: pending
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create a JSON file for Testing Farm in order to schedule a CI testing job
          cat << EOF > pending.json
          {
            "sha": "${{steps.sha.outputs.SHA}}",
            "state": "pending",
            "context": "Testing Farm - RHEL7",
            "target_url": "http://artifacts.osci.redhat.com/testing-farm/${{ steps.sched_test.outputs.req_id }}/"
          }
          EOF
          echo "https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/${{steps.sha.outputs.SHA}}"
          # GITHUB_TOKEN is used for updating pull request status.
          # It is provided by GitHub https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/${{steps.sha.outputs.SHA}} \
            --data @pending.json
          echo "::set-output name=GITHUB_REPOSITORY::$GITHUB_REPOSITORY"

      - name: Schedule a test on Testing Farm for RHEL7
        id: sched_test
        run: |
          # Update ubuntu-20.04 in order to install curl and jq
          apt update && apt -y install curl jq
          cat << EOF > request.json
          {
            "api_key": "${{ secrets.TF_INTERNAL_API_KEY }}",
            "test": {"fmf": {
              "url": "https://gitlab.cee.redhat.com/platform-eng-core-services/sclorg-tmt-plans",
              "ref": "master",
              "name": "rhel7-docker"
            }},
            "environments": [{
              "arch": "x86_64",
              "os": {"compose": "RHEL-7.9-Released"},
              "variables": {
                "REPO_URL": "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY",
                "REPO_NAME": "$GITHUB_REPOSITORY",
                "PR_NUMBER": "${{ steps.pr_nr.outputs.PR_NR }}",
                "OS": "rhel7",
                "TEST_NAME": "test"
              }
            }]
          }
          EOF
          curl ${{ secrets.TF_ENDPOINT }}/requests --data @request.json --header "Content-Type: application/json" --output response.json
          # Store REQ_ID into outputs for later on usage
          echo "::set-output name=REQ_ID::$(jq -r .id response.json)"

  running:
    needs: build
    name: Check running tests on Testing Farm service for RHEL7
    runs-on: ubuntu-20.04
    outputs:
      REQ_ID: ${{steps.req_sha.outputs.REQ_ID}}
      SHA: ${{steps.req_sha.outputs.SHA}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check if REQ_ID and SHA exists
        id: req_sha
        run: |
          # Update ubuntu-20.04 in order to install curl and jq
          # each job is separate machine
          apt update && apt -y install curl jq
          # Propagate REQ_ID and SHA into the finish section
          echo "::set-output name=REQ_ID::${{needs.build.outputs.REQ_ID}}"
          echo "::set-output name=SHA::${{needs.build.outputs.SHA}}"

      - name: Switch to running state of Testing Farm request for RHEL7
        id: running
        run: |
          # Create running.json file for query, whether job is finished or not.
          cat << EOF > running.json
          {
            "sha": "${{needs.build.outputs.SHA}}",
            "state": "pending",
            "context": "Testing Farm - RHEL7",
            "description": "Build started",
            "target_url": "http://artifacts.osci.redhat.com/testing-farm/${{ needs.build.outputs.REQ_ID }}"
          }
          EOF
          # Update GitHub status description to 'Build started'
          curl -X POST -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/${{needs.build.outputs.SHA}} \
            --data @running.json

      - name: Check test is still running
        id: still_running
        run: |
          CMD=${{ secrets.TF_ENDPOINT }}/requests/${{needs.build.outputs.REQ_ID}}
          curl $CMD > job.json
          state=$(jq -r .state job.json)
          # Wait till job is not finished. As soon as state is complete or failure then go to the finish action
          while [ "$state" == "running" ] || [ "$state" == "new" ] || [ "$state" == "pending" ] || [ "$state" == "queued" ]; do
            # Wait 30s. We do not need to query Testing Farm each second
            sleep 30
            curl $CMD > job.json
            state=$(jq -r .state job.json)
          done

  finish:
    needs: running
    name: Tests are finished - switching to proper state for RHEL7
    runs-on: ubuntu-20.04
    steps:
      - name: Check if REQ_ID exists
        run: echo "${{ needs.running.outputs.REQ_ID }}"

      - name: Check if SHA exists
        run: echo "${{ needs.running.outputs.SHA }}"

      - name: Get final state of Testing Farm request for RHEL7
        id: final_state
        run: |
          # Update ubuntu-20.04 in order to install curl and jq
          # each job is separate machine
          apt update && apt -y install curl jq
          curl ${{ secrets.TF_ENDPOINT }}/requests/${{needs.running.outputs.REQ_ID}} > job.json
          cat job.json
          state=$(jq -r .state job.json)
          result=$(jq -r .result.overall job.json)
          new_state="success"
          infra_error=" "
          echo "State is $state and result is: $result"
          if [ "$state" == "complete" ]; then
            if [ "$result" != "passed" ]; then
              new_state="failure"
            fi
          else
            # Mark job in case of infrastructure issues. Report to Testing Farm team
            infra_error=" - Infra problems"
            new_state="failure"
          fi
          echo "New State is: $new_state"
          echo "Infra state is: $infra_error"
          echo "::set-output name=FINAL_STATE::$new_state"
          echo "::set-output name=INFRA_STATE::$infra_error"

      - name: Switch to final state of Testing Farm request for RHEL7
        run: |
          cat << EOF > final.json
          {
            "sha": "${{needs.running.outputs.SHA}}",
            "state": "${{steps.final_state.outputs.FINAL_STATE}}",
            "context": "Testing Farm - RHEL7",
            "description": "Build finished${{steps.final_state.outputs.INFRA_STATE}}",
            "target_url": "http://artifacts.osci.redhat.com/testing-farm/${{ needs.running.outputs.REQ_ID }}"
          }
          EOF
          cat final.json
          # Switch Github status to proper state
          curl -X POST -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/${{needs.running.outputs.SHA}} \
            --data @final.json
